<?php

namespace App\Twig;

use Twig\Extension\AbstractExtension;
use Twig\TwigFilter;
use Twig\TwigFunction;


class ParserJBBCodeExtension extends AbstractExtension
{
    public function getFilters(): array
    {
        return [
            // If your filter generates SAFE HTML, you should add a third
            // parameter: ['is_safe' => ['html']]
            // Reference: https://twig.symfony.com/doc/2.x/advanced.html#automatic-escaping
            new TwigFilter('filter_name', [$this, 'doSomething']),
        ];
    }

    public function getFunctions(): array
    {
        return [
            new TwigFunction('parser', [$this, 'parserJBBCode']),
            new TwigFunction('delParser', [$this, 'deleteJBBCode']),
        ];
    }

    public function parserJBBCode($text)
    {
        // BBcode array
      	$find = array(
            '~\[br]~s',
      		'~\[b\](.*?)\[/b\]~s',
      		'~\[i\](.*?)\[/i\]~s',
      		'~\[u\](.*?)\[/u\]~s',
            '~\[s\](.*?)\[/s\]~s',
            '~\[left\](.*?)\[/left\]~s',
            '~\[center\](.*?)\[/center\]~s',
            '~\[right\](.*?)\[/right\]~s',
      		'~\[quote\](.*?)\[/quote\]~s',
      		'~\[size=(.*?)\](.*?)\[/size\]~s',
            '~\[font=(.*?)\](.*?)\[/font\]~s',
      		'~\[color=(.*?)\](.*?)\[/color\]~s',
      		'~\[url=((?:ftp|https?)://.*?)\](.*?)\[/url\]~s',
      		'~\[img\](https?://.*?\.(?:jpg|jpeg|gif|png|bmp))\[/img\]~s',
            '~\[code\](.*?)\[/code\]~s',
            '~\[list\](.*?)\[/list\]~s',
            '~\[ol\](.*?)\[/ol\]~s',
            '~\[li\](.*?)\[/li\]~s',
            '~\[table\](.*?)\[/table\]~s',
            '~\[tr\](.*?)\[/tr\]~s',
            '~\[td\](.*?)\[/td\]~s',
            '~\:abruti:~s',
            '~\:boulet:~s',
            '~\:clin:~s',
            '~\lol~s',
            '~\:modo:~s',
            '~\:ninja:~s',
            '~\:smile1:~s',
            '~\:troll:~s',
            '~\:troll1:~s',
            '~\:infectionpc:~s',
            '~\:matrix:~s',
            '~\:mdr1:~s',
            '~\:hacker:~s',
            '~\:virusdown:~s',
            '~\:anonymous:~s',
            '~\:nettoyage:~s',
            '~\:anonymous1:~s',
            '~\:cabug:~s',
            '~\:games:~s',
            '~\:2guns:~s',
            '~\:banned:~s',
            '~\:baver:~s',
            '~\:beurk:~s',
            '~\:bizarr:~s',
            '~\:bravo:~s',
            '~\:bye:~s',
            '~\:crazy:~s',
            '~\:dessert:~s',
            '~\:disput:~s',
            '~\:doublefuck:~s',
            '~\:elmojito:~s',
            '~\:express:~s',
            '~\:love:~s',
            '~\:matraque:~s',
            '~\:mdr2:~s',
            '~\:null:~s',
            '~\:ok:~s',
            '~\:pile:~s',
            '~\:fumeur:~s',
            '~\:sallum:~s',
            '~\:sivier:~s',
            '~\:sniper:~s',
            '~\:superm:~s',
            '~\:ta_pas:~s',
            '~\:tchuss:~s',
            '~\:timide:~s',
            '~\:trollm:~s',
            '~\:tu_con:~s',
            '~\:un_ver:~s',
            '~\:vainqu:~s',
            '~\:welcomeweb:~s',
            '~\zouzou~s',
            '~\:piou:~s',
            '~\:newbie:~s',
            '~\:nooby:~s',
            '~\:but_cir:~s',
            '~\:but_l1:~s',
            '~\:but_l2:~s',
            '~\:but_l3:~s',
            '~\:but_ps:~s',
            '~\:but_r1:~s',
            '~\:but_r2:~s',
            '~\:but_r3:~s',
            '~\:but_select:~s',
            '~\:but_square:~s',
            '~\:but_start:~s',
            '~\:but_tri:~s',
            '~\:but_x:~s',
            '~\:dir_down:~s',
            '~\:dir_left:~s',
            '~\:dir_right:~s',
            '~\:dir_up:~s',
            '~\:left_down:~s',
            '~\:left_left:~s',
            '~\:left_right:~s',
            '~\:left_up:~s',
            '~\:right_down:~s',
            '~\:right_left:~s',
            '~\:right_right:~s',
            '~\:right_up:~s',

      	);
      	// HTML tags to replace BBcode
      	$replace = array(
            '<br/>',
      		'<b>$1</b>',
      		'<i>$1</i>',
      		'<span style="text-decoration:underline;">$1</span>',
            '<strike>$1</strike>',
            '<div style="text-align:left;">$1</div>',
            '<div style="text-align:center;">$1</div>',
            '<div style="text-align:right;">$1</div>',
      		'<pre>$1</'.'pre>',
      		'<span style="font-size:$1px;">$2</span>',
            '<span style="font-family:$1px;">$2</span>',
      		'<span style="color:$1;">$2</span>',
      		'<a href="$1">$1</a>',
      		'<img src="$1" alt="" />',
            '<code>$1</code>',
            '<ul>$1</ul>',
            '<ol>$1</ol>',
            '<li>$1</li>',
            '<table class="table table-responsive">$1</table>',
            '<tr>$1</tr>',
            '<td>$1</td>',
            '<img src="/assets/img/smileys/abruti.gif" alt=":abruti:" />',
            '<img src="/assets/img/smileys/boulet.gif" alt=":boulet:" />',
            '<img src="/assets/img/smileys/clin.gif" alt=":clin:" />',
            '<img src="/assets/img/smileys/lol.gif" alt="lol" />',
            '<img src="/assets/img/smileys/modo.gif" alt=":modo:" />',
            '<img src="/assets/img/smileys/ninja.gif" alt=":ninja:" />',
            '<img src="/assets/img/smileys/simley.png" alt=":smile1:" />',
            '<img src="/assets/img/smileys/troll/1.png" alt=":troll:" />',
            '<img src="/assets/img/smileys/troll/troll.png" alt=":troll1:" />',
            '<img src="/assets/img/smileys/informatique/infect10.gif" alt=":infectionpc:" />',
            '<img src="/assets/img/smileys/informatique/smiley10.gif" alt=":matrix:" />',
            '<img src="/assets/img/smileys/informatique/mdr1.gif" alt=":mdr1:" />',
            '<img src="/assets/img/smileys/informatique/hacker10.gif" alt=":hacker:" />',
            '<img src="/assets/img/smileys/informatique/virusdown.gif" alt=":virusdown:" />',
            '<img src="/assets/img/smileys/informatique/anonymous.png" alt=":anonymous:" />',
            '<img src="/assets/img/smileys/nettoyage.gif" alt=":nettoyage:" />',
            '<img src="/assets/img/smileys/informatique/annony10.gif" alt=":anonymous1:" />',
            '<img src="/assets/img/smileys/informatique/cabug10.gif" alt=":cabug:" />',
            '<img src="/assets/img/smileys/games.gif" alt=":games:" />',
            '<img src="/assets/img/smileys/2guns.gif" alt=":2guns:" />',
            '<img src="/assets/img/smileys/banned.gif" alt=":banned:" />',
            '<img src="/assets/img/smileys/baver.gif" alt=":baver:" />',
            '<img src="/assets/img/smileys/beurk.gif" alt=":beurk:" />',
            '<img src="/assets/img/smileys/bizarr.gif" alt=":bizarr:" />',
            '<img src="/assets/img/smileys/bravo.gif" alt=":bravo:" />',
            '<img src="/assets/img/smileys/bye.gif" alt=":bye:" />',
            '<img src="/assets/img/smileys/crazy.gif" alt=":crazy:" />',
            '<img src="/assets/img/smileys/dessert.gif" alt=":dessert:" />',
            '<img src="/assets/img/smileys/disput.gif" alt=":disput:" />',
            '<img src="/assets/img/smileys/doublefuck.gif" alt=":doublefuck:" />',
            '<img src="/assets/img/smileys/elmojito.gif" alt=":elmojito:" />',
            '<img src="/assets/img/smileys/express.gif" alt=":express:" />',
            '<img src="/assets/img/smileys/love.gif" alt=":love:" />',
            '<img src="/assets/img/smileys/matraque.gif" alt=":matraque:" />',
            '<img src="/assets/img/smileys/mdr2.gif" alt=":mdr2:" />',
            '<img src="/assets/img/smileys/null.gif" alt=":null:" />',
            '<img src="/assets/img/smileys/ok.gif" alt=":ok:" />',
            '<img src="/assets/img/smileys/pile.gif" alt=":pile:" />',
            '<img src="/assets/img/smileys/fumeur.gif" alt=":fumeur:" />',
            '<img src="/assets/img/smileys/sallum.gif" alt=":sallum:" />',
            '<img src="/assets/img/smileys/sivier.gif" alt=":sivier:" />',
            '<img src="/assets/img/smileys/sniper.gif" alt=":sniper:" />',
            '<img src="/assets/img/smileys/superm.gif" alt=":superm:" />',
            '<img src="/assets/img/smileys/ta_pas.gif" alt=":ta_pas:" />',
            '<img src="/assets/img/smileys/tchuss.gif" alt=":tchuss:" />',
            '<img src="/assets/img/smileys/timide.gif" alt=":timide:" />',
            '<img src="/assets/img/smileys/trollm.gif" alt=":trollm:" />',
            '<img src="/assets/img/smileys/tu_con.gif" alt=":tu_con:" />',
            '<img src="/assets/img/smileys/un_ver.gif" alt=":un_ver:" />',
            '<img src="/assets/img/smileys/vainqu.gif" alt=":vainqu:" />',
            '<img src="/assets/img/smileys/welcomeweb.gif" alt=":welcomeweb:" />',
            '<img src="/assets/img/smileys/zouzou.gif" alt=":zouzou:" />',
            '<img src="/assets/img/smileys/piou.gif" alt=":piou:" />',
            '<img src="/assets/img/smileys/troll/newbie.gif" alt=":newbie:" />',
            '<img src="/assets/img/smileys/troll/nooby.gif" alt=":nooby:" />',
            '<img src="/assets/img/smileys/playstation/but_cir.png" alt=":but_cir:" />',
            '<img src="/assets/img/smileys/playstation/but_l1.png" alt=":but_l1:" />',
            '<img src="/assets/img/smileys/playstation/but_l2.png" alt=":but_l2:" />',
            '<img src="/assets/img/smileys/playstation/but_l3.png" alt=":but_l3:" />',
            '<img src="/assets/img/smileys/playstation/but_ps.png" alt=":but_ps:" />',
            '<img src="/assets/img/smileys/playstation/but_r1.png" alt=":but_r1:" />',
            '<img src="/assets/img/smileys/playstation/but_r2.png" alt=":but_r2:" />',
            '<img src="/assets/img/smileys/playstation/but_r3.png" alt=":but_r3:" />',
            '<img src="/assets/img/smileys/playstation/but_select.png" alt=":but_select:" />',
            '<img src="/assets/img/smileys/playstation/but_square.png" alt=":but_square:" />',
            '<img src="/assets/img/smileys/playstation/but_start.png" alt=":but_start:" />',
            '<img src="/assets/img/smileys/playstation/but_tri.png" alt=":but_tri:" />',
            '<img src="/assets/img/smileys/playstation/but_x.png" alt=":but_x:" />',
            '<img src="/assets/img/smileys/playstation/dir_down.png" alt=":dir_down:" />',
            '<img src="/assets/img/smileys/playstation/dir_left.png" alt=":dir_left:" />',
            '<img src="/assets/img/smileys/playstation/dir_right.png" alt=":dir_right:" />',
            '<img src="/assets/img/smileys/playstation/dir_up.png" alt=":dir_up:" />',
            '<img src="/assets/img/smileys/playstation/left_down.png" alt=":left_down:" />',
            '<img src="/assets/img/smileys/playstation/left_left.png" alt=":left_left:" />',
            '<img src="/assets/img/smileys/playstation/left_right.png" alt=":left_right:" />',
            '<img src="/assets/img/smileys/playstation/left_up.png" alt=":left_up:" />',
            '<img src="/assets/img/smileys/playstation/right_down.png" alt=":right_down:" />',
            '<img src="/assets/img/smileys/playstation/right_left.png" alt=":right_left:" />',
            '<img src="/assets/img/smileys/playstation/right_right.png" alt=":right_right:" />',
            '<img src="/assets/img/smileys/playstation/right_up.png" alt=":right_up:" />',
      	);
      	// Replacing the BBcodes with corresponding HTML tags
      	return preg_replace($find,$replace,$text);
    }

    public function deleteJBBCode($value)
    {
        return preg_replace('/\[(.*?)\]/ism','', $value) ;
    }

    public function doSomething($value)
    {
    }
}
