vich_uploader:
    db_driver: orm

    mappings:
        avatar_image:
            uri_prefix: /data/avatar
            upload_destination: '%kernel.project_dir%/public/data/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: false
