easy_admin:
    site_name: '<span class="logoAnim">LMoury</span>'
    formats:
        date: 'j M Y'
        datetime: 'j M Y H:i'
    list:
        actions:
            - {name: 'edit', icon: 'edit', label: false, css_class: 'btn btn-primary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}

    new:
        actions:
            - {name: 'list',  icon: 'sign-out', label: false, css_class: 'btn btn-secondary'}
    edit:
        actions:
            - {name: 'list',  icon: 'sign-out', label: false, css_class: 'btn btn-secondary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
    show:
        actions:
            - {name: 'list',  icon: 'sign-out', label: false, css_class: 'btn btn-secondary'}
            - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
            - {name: 'edit', icon: 'edit', label: false, css_class: 'btn btn-primary'}
