easy_admin:
    design:
        assets:
            css:
                - '/assets/css/admin.css'
                - '/assets/css/username.css'
        menu:
            - label: 'Dashboard'
              icon: 'dashboard'
              children:
                  - {label: 'Dashboard', icon: 'dashboard', route: 'admin.dashboard', default: true }
                  - {entity: 'Config', icon: 'cogs', label: 'Paramètre général'}
                  - {label: 'Statistiques', icon: 'bar-chart-o', route: 'admin.statistique' }
                  - {entity: 'Notice', icon: 'sticky-note', label: 'Notice'}
                  - {entity: 'Social', icon: 'share-alt', label: 'Médias sociaux'}
            - label: 'Utilisateurs'
              icon: 'users'
              children:
                  - {entity: 'User', icon: 'users', label: 'Liste des utilisateurs'}
                  - {entity: 'User', icon: 'user', label: 'Créer un utilisateur', params: { action: 'new' } }
                  - {entity: 'Administrateurs', label: 'Administrateurs', icon: 'code'}
                  - {entity: 'Moderateurs', label: 'Modérateurs', icon: 'shield'}
                  - {entity: 'Banni', label: 'Utilisateur banni', icon: 'user-times'}
                  - {entity: 'UserRole', icon: 'graduation-cap', label: 'Roles des utilisateurs'}
            - label: 'Forums'
              icon: 'comments'
              children:
                  - {label: 'Liste des forums', icon: 'list-ol', route: 'admin.categories' }
                  - {entity: 'ForumCategorie', icon: 'inbox', label: 'Créer une catégorie', params: { action: 'new' } }
                  - {label: 'Créer un nouveau forum', icon: 'inbox', route: 'admin.categorie.new' }
                  - {entity: 'Tag', icon: 'tags', label: 'Tags'}
                  - {label: 'Prefixe', icon: 'list-ol', route: 'admin.prefixes' }
            - {label: 'Templates', icon: 'file', route: 'admin.templates' }
            - {label: 'Logs', icon: 'link', route: 'admin.auditlog' }
            - {entity: 'Contact', icon: 'envelope', label: 'Contact'}
