easy_admin:
    entities:
        ForumCategorie:
            list:
                title: 'Créer un nouveau forum'
                actions:
                    - { name: 'show', icon: 'eye', label: false, css_class: 'btn btn-primary' }
            new:
                title: 'Créer un nouveau forum'
            edit:
                title: 'Editer le forum'
            class: App\Entity\ForumCategorie
            form:
                fields:
                    - {property: 'categorie'}
                    - {property: 'access'}
                    - {property: 'icon'}
                    - {property: 'ordre'}
        Tag:
            class: App\Entity\Tag
            list:
                title: 'Tag'
            new:
                title: 'Nouveau tag'
            edit:
                title: 'Editer le tag'
            form:
                fields:
                    - {property: 'nom'}
